"""beta_c counts on P1's frozen 1,000-item set. Measurement only, no design.

K2 fired (`reports/T2_k2_gate.md`), so the beta_c-stratified redraw does not
happen and D2's pre-specified fallback is reuse of P1's frozen
`items_final.parquet`. This script measures what that set contains before the
fallback is adopted. It selects nothing and designs nothing.

**No sample may be selected on finite `beta_c`.** That is selection on the
dependent variable: Arm B's confirmatory analysis set is defined by finite
`beta_c`, so enriching a draw for it would guarantee the contrast it is supposed
to test. If a count below is short, the admissible responses are a larger sample
drawn without reference to `beta_c`, or a stated power limitation. This comment
is here because the counts this script prints are exactly what would tempt the
other choice.

`beta_c` by T1's `adversary.beta_critical_batch`; `fit_cost` and `conflict` read
from P1's frozen artifact, not recomputed. Deterministic, no seed.

Run: python3 src/frozen_set_beta_c.py     (writes reports/T2_frozen_set_counts.md)
"""
import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import adversary as adv  # noqa: E402
import p1  # noqa: E402

TILES = ("manmade", "moves", "hold", "size")
SIZE_TARGET = 400        # preregistration v2.0 section 8.2, provisional
REPORT = "reports/T2_frozen_set_counts.md"

# Pool existence rates |D(inf)|/N, from PREREGISTRATION_v2.1 section 1.2 (T1's
# benchmark over the full 200k pool). Quoted, not recomputed: this script's job
# is to compare the frozen set against them.
POOL_RATE = {"pooled": 0.1823, "manmade": 0.0387, "moves": 0.1790,
             "hold": 0.1775, "size": 0.3338}


def pool_conflict_rate():
    """Share of the 200k pool with `fit_cost > 0`, from the K2 gate's table."""
    import pandas as pd
    return float((pd.read_parquet("data/pool_beta_c.parquet")["fit_cost"] > 0).mean())


def qualifying_pool():
    """{tile: conflict items in the 200k pool passing P1's own selection gates}.

    P1's gates, verbatim from `final_items.py` Step 5:
    `resample_stability >= 0.95` and `family_agree`. This is the ceiling a draw
    under P1's recipe could reach on the conflict half without relaxing anything
    P1 fixed. Read from the frozen scored artifact, not recomputed.
    """
    import pandas as pd
    s = pd.read_parquet(p1.ITEMS_SCORED,
                        columns=["tile", "conflict", "resample_stability",
                                 "family_agree"])
    keep = (s["resample_stability"] >= 0.95) & s["family_agree"] & s["conflict"]
    return s[keep]["tile"].value_counts().to_dict()


def main():
    t0 = time.perf_counter()
    df = p1.load_items()
    bc = np.empty(len(df))
    for tile in TILES:
        ix = np.where(df["tile"].values == tile)[0]
        bc[ix] = adv.beta_critical_batch(
            adv.build_batch(df.iloc[ix].reset_index(drop=True)))
    fin = np.isfinite(bc)
    fc = df["fit_cost"].values.astype(float)
    conflict = df["conflict"].values.astype(bool)
    n = len(df)

    lines = []
    w = lines.append
    w("# T2 Step 1: `beta_c` on P1's frozen 1,000-item set\n")
    w(f"\nGenerated by `python3 src/frozen_set_beta_c.py` on "
      f"{time.strftime('%Y-%m-%d')}. Deterministic, no seed. "
      f"Measurement only: this script selects nothing and designs nothing.\n")
    w("\nContext: K2 fired (`reports/T2_k2_gate.md`, "
      "`rho_Spearman = -0.9036`), so the `beta_c`-stratified redraw does not "
      "happen and D2's pre-specified fallback is reuse of this frozen set. "
      "These are the counts that fallback would inherit.\n")

    w("\n## 1 and 2. Finite-`beta_c` count and share, against the pool rate\n\n")
    w("| set | N | finite `beta_c` | share | pool rate `\\|D(inf)\\|/N` | difference |\n")
    w("|---|---:|---:|---:|---:|---:|\n")
    rows = [("**pooled**", np.ones(n, bool), "pooled")]
    rows += [(f"`{t}` (\\|O\\| = {adv.tile_k(t)})", df["tile"].values == t, t)
             for t in TILES]
    for name, m, key in rows:
        share = fin[m].mean()
        w(f"| {name} | {int(m.sum()):,} | {int(fin[m].sum()):,} | "
          f"{share:.4f} | {POOL_RATE[key]:.4f} | {share - POOL_RATE[key]:+.4f} |\n")
    w("\nPool rates are quoted from `PREREGISTRATION_v2.1` section 1.2 (T1's "
      "benchmark over the full 200,000-candidate pool), not recomputed here.\n")

    w("\n### The enrichment is benign, for two independent reasons\n")
    p_conf = conflict.mean()
    r_conf, r_non = fin[conflict].mean(), fin[~conflict].mean()
    pred = p_conf * r_conf + (1 - p_conf) * r_non
    w(f"\nP1's draw is **{p_conf:.0%} conflict by construction**: "
      f"`final_items.py` Step 5 fills a fixed quota of {int(conflict.sum()) // 4} "
      f"conflict and {int((~conflict).sum()) // 4} non-conflict items per tile. "
      f"The pool is {pool_conflict_rate():.4f} conflict. Conflict items are "
      f"where the adversary bites (finite-`beta_c` rate {r_conf:.4f} against "
      f"{r_non:.4f} on non-conflict items), so a set built half of them carries "
      f"a higher finite-`beta_c` rate mechanically:\n\n"
      f"```\n{p_conf:.2f} * {r_conf:.4f}  +  {1 - p_conf:.2f} * {r_non:.4f}"
      f"  =  {pred:.4f}      observed {fin.mean():.4f}\n```\n")
    w("\n**Reason 1, provenance.** The enrichment is entirely P1's conflict "
      "quota, which was fixed for P1's own reasons before `beta_c` existed as a "
      "quantity. Nothing in the frozen set was selected with any knowledge of "
      "`beta_c`, so reusing it does not select on the dependent variable.\n")
    w("\n**Reason 2, estimand.** Selection on the dependent variable corrupts a "
      "**prevalence** estimate. Prevalence is Arm A's question, and Arm A "
      "measures it on the 200,000-candidate pool, not on the item set "
      "(preregistration v2.0 section 7.1; T6 Step 1). Arm B measures "
      "**movement within** the divergence set, conditional on membership, so "
      "enrichment costs that estimate nothing and buys it power. The two "
      "reasons are independent: either alone would settle it.\n")
    w("\nRecorded as benign, not as a defect. The prohibition it might look "
      "like it violates is on a *new draw* reaching for finite `beta_c` "
      "deliberately, which would enrich the analysis set by the very criterion "
      "that defines it. Inheriting an enrichment that fell out of an unrelated "
      "quota is not that, and neither is a larger draw under P1's own recipe.\n")

    w("\n## 3. The `size` tile against the preregistered target\n\n")
    m = df["tile"].values == "size"
    got = int(fin[m].sum())
    w(f"```\nsize-tile items with finite beta_c   {got}\n"
      f"preregistration v2.0 section 8.2 target   {SIZE_TARGET}  (provisional)\n"
      f"shortfall                                 {max(0, SIZE_TARGET - got)}\n"
      f"fraction of target                        {got / SIZE_TARGET:.3f}\n```\n")
    w(f"\nThe frozen set holds {int(m.sum())} `size`-tile items in total, so "
      f"{SIZE_TARGET} finite-`beta_c` items is not reachable from this set at "
      f"any selection rule: the ceiling is {int(m.sum())} and the observed rate "
      f"is {fin[m].mean():.4f}. The target is provisional in any case "
      f"(section 8.2: `sigma` has never been measured and the 400 is a curve "
      f"over an assumption, not a computed requirement).\n")
    w("\n**Not a licence to enrich.** Arm B's confirmatory analysis set is "
      "defined by finite `beta_c`, so a draw that selected on finite `beta_c` "
      "would be selection on the dependent variable. Section 8.2's own "
      "fallbacks are a larger sample drawn without reference to `beta_c`, or a "
      "stated power limitation.\n")

    w("\n## 4. Conflict-set overlap\n\n")
    w("Of the finite-`beta_c` items, how many carry `fit_cost > 0`:\n\n")
    w("| set | finite `beta_c` | of those, `fit_cost > 0` | share |\n")
    w("|---|---:|---:|---:|\n")
    for name, m, _ in rows:
        f2 = m & fin
        k = int((fc[f2] > 0).sum())
        w(f"| {name} | {int(f2.sum()):,} | {k:,} | "
          f"{k / max(1, int(f2.sum())):.4f} |\n")
    bad = int((conflict != (fc > 0)).sum())
    w(f"\n`fit_cost > 0` and P1's `conflict` flag agree on "
      f"{n - bad:,} of {n:,} items, so the column above is P1's conflict set "
      f"read through `fit_cost`, not a second definition.\n")
    w("\nThe complementary direction, for the same reason the pooled K2 "
      "coefficient came out where it did:\n\n")
    w("| set | N | finite `beta_c` and `fit_cost > 0` | finite `beta_c` and "
      "`fit_cost = 0` |\n|---|---:|---:|---:|\n")
    for name, m, _ in rows:
        f2 = m & fin
        w(f"| {name} | {int(m.sum()):,} | {int((fc[f2] > 0).sum()):,} | "
          f"{int((fc[f2] == 0).sum()):,} |\n")
    w(f"\nAmong conflict items the finite-`beta_c` rate is "
      f"{fin[conflict].mean():.4f} ({int(fin[conflict].sum()):,} of "
      f"{int(conflict.sum()):,}); among non-conflict items it is "
      f"{fin[~conflict].mean():.4f} ({int(fin[~conflict].sum()):,} of "
      f"{int((~conflict).sum()):,}).\n")

    w("\n## 5. Projection: N required to reach 400 per tile under P1's own recipe\n")
    w("\nArithmetic only. This is a projection from the rates measured above, "
      "not a sample and not a design. The recipe held fixed is P1's, unchanged: "
      "`final_items.py` Step 5's 50/50 conflict/non-conflict split per tile, "
      "`fit_cost` deciles within the conflict half, `decision_margin` deciles "
      "within the non-conflict half. `beta_c` enters nowhere in it, which is "
      "what makes the projection admissible at all.\n")
    w(f"\nUnder that recipe a tile's finite-`beta_c` rate is the rate measured "
      f"above, so the tile size needed for {SIZE_TARGET} such items is "
      f"`ceil({SIZE_TARGET} / r_t)`. The 95% interval carries the binomial "
      f"uncertainty in `r_t` itself, which is estimated from 250 items per "
      f"tile and is the dominant error here.\n\n")
    w(f"| tile | `r_t` measured | items/tile for {SIZE_TARGET} | 95% interval "
      f"| conflict items needed | qualifying conflicts in pool | feasible |\n")
    w("|---|---:|---:|---:|---:|---:|---:|\n")
    qual = qualifying_pool()
    total, total_lo, total_hi = 0, 0, 0
    for t in TILES:
        m = df["tile"].values == t
        r = fin[m].mean()
        se = np.sqrt(r * (1 - r) / int(m.sum()))
        n_t = int(np.ceil(SIZE_TARGET / r))
        n_hi = int(np.ceil(SIZE_TARGET / max(r - 1.96 * se, 1e-9)))
        n_lo = int(np.ceil(SIZE_TARGET / min(r + 1.96 * se, 1.0)))
        need_c = int(np.ceil(n_t / 2))
        have_c = qual[t]
        total += n_t
        total_lo += n_lo
        total_hi += n_hi
        w(f"| `{t}` | {r:.4f} | **{n_t:,}** | {n_lo:,} to {n_hi:,} | "
          f"{need_c:,} | {have_c:,} | "
          f"{'yes' if need_c <= have_c else '**NO**'} |\n")
    w(f"| **total** | | **{total:,}** | {total_lo:,} to {total_hi:,} | "
      f"{int(np.ceil(total / 2)):,} | {sum(qual.values()):,} | |\n")
    w(f"\nSo **{total:,} items, roughly {total // 4:,} per tile**, to put "
      f"{SIZE_TARGET} finite-`beta_c` items on every tile, against P1's 1,000. "
      f"The `size` tile alone needs {int(np.ceil(SIZE_TARGET / fin[df['tile'].values == 'size'].mean())):,}.\n")
    w("\n**Feasibility.** The conflict half is the binding side: it is the "
      "scarcer stratum in the pool and it carries almost all the finite-"
      "`beta_c` items. The 'qualifying conflicts in pool' column counts pool "
      "items passing P1's own selection gates "
      "(`resample_stability >= 0.95` and `family_agree`) on that tile, which is "
      "the ceiling a draw under P1's recipe could reach without relaxing "
      "anything P1 fixed.\n")
    tight = min(TILES, key=lambda t: qual[t] / np.ceil(
        np.ceil(SIZE_TARGET / fin[df["tile"].values == t].mean()) / 2))
    m = df["tile"].values == tight
    r = fin[m].mean()
    se = np.sqrt(r * (1 - r) / int(m.sum()))
    need = np.ceil(np.ceil(SIZE_TARGET / r) / 2)
    need_hi = np.ceil(np.ceil(SIZE_TARGET / max(r - 1.96 * se, 1e-9)) / 2)
    w(f"\nEvery tile clears, but not with the same room. `{tight}` is the "
      f"binding one: it would take **{need / qual[tight]:.0%}** of its "
      f"qualifying conflict items at the point estimate and "
      f"**{need_hi / qual[tight]:.0%}** at the interval's upper end, against "
      f"{min(np.ceil(np.ceil(SIZE_TARGET / fin[df['tile'].values == t].mean()) / 2) / qual[t] for t in TILES if t != tight):.0%} "
      f"or less on the other three. At that utilisation the draw is close to a "
      f"census of the tile's qualifying conflicts, so P1's within-conflict "
      f"`fit_cost` deciles stay fillable only because they are equal-count by "
      f"construction; a decile-level shortfall would surface as "
      f"`final_items.py`'s 'unfillable strata' rather than silently. Stated as "
      "a fact about the arithmetic, not as an objection to any path.\n")
    w("\n**What this projection is not.** It does not say the redraw should "
      "happen, how large it should be, or whether 400 per tile is the right "
      "target. `SIZE_TARGET` is preregistration section 8.2's provisional "
      "figure, resting on a `sigma` nothing has measured; if `sigma` moves, "
      "every number in this table moves with it. The unit-of-analysis question "
      "underneath it (per-tile primary, or pooled with tile as a stratum) is a "
      "preregistration matter and is handed to T5 in "
      "`docs/P2/PREREGISTRATION_v2.2.md` section 4, not decided here.\n")

    w("\n## Chain of custody\n\n")
    w(f"Spec version `{adv.SPEC_VERSION}`. `beta_c` by "
      f"`adversary.beta_critical_batch` (bisected value of record, "
      f"`eps_beta = {adv.EPS_BETA:g}`).\n\n")
    w("| artifact | sha256 |\n|---|---|\n")
    w(f"| `items_final.parquet` | `{p1.artifact_hash(p1.ITEMS_FINAL)}` |\n")
    w(f"\nRuntime {time.perf_counter() - t0:.1f} s.\n")

    os.makedirs(os.path.dirname(REPORT), exist_ok=True)
    with open(REPORT, "w") as fh:
        fh.write("".join(lines))

    print(f"frozen set N = {n:,}   finite beta_c = {int(fin.sum()):,} "
          f"({fin.mean():.4f}, pool {POOL_RATE['pooled']:.4f})")
    for t in TILES:
        m = df["tile"].values == t
        print(f"  {t:8s} {int(fin[m].sum()):>4} / {int(m.sum()):>4}  "
              f"({fin[m].mean():.4f}, pool {POOL_RATE[t]:.4f})")
    print(f"size tile finite beta_c = {int(fin[df['tile'].values == 'size'].sum())}"
          f"  vs provisional target {SIZE_TARGET}")
    print(f"of {int(fin.sum()):,} finite-beta_c items, "
          f"{int((fc[fin] > 0).sum()):,} have fit_cost > 0")
    print(f"written: {REPORT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
