"""beta_c counts on P1's frozen 1,000-item set. Measurement only, no design.

K2 fired (`reports/T2_k2_gate.md`), so the beta_c-stratified redraw does not
happen and D2's pre-specified fallback is reuse of P1's frozen
`items_final.parquet`. This script measures what that set contains before the
fallback is adopted. It selects nothing and designs nothing.

**No sample may be selected on finite `beta_c`.** That is selection on the
dependent variable: Arm B's confirmatory analysis set is defined by finite
`beta_c`, so enriching a draw for it would guarantee the contrast it is supposed
to test. If a count below is short, the admissible responses are a larger sample
drawn without reference to `beta_c`, or a stated power limitation. This comment
is here because the counts this script prints are exactly what would tempt the
other choice.

`beta_c` by T1's `adversary.beta_critical_batch`; `fit_cost` and `conflict` read
from P1's frozen artifact, not recomputed. Deterministic, no seed.

Run: python3 src/frozen_set_beta_c.py     (writes reports/T2_frozen_set_counts.md)
"""
import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import adversary as adv  # noqa: E402
import p1  # noqa: E402

TILES = ("manmade", "moves", "hold", "size")
SIZE_TARGET = 400        # preregistration v2.0 section 8.2, provisional
REPORT = "reports/T2_frozen_set_counts.md"

# Pool existence rates |D(inf)|/N, from PREREGISTRATION_v2.1 section 1.2 (T1's
# benchmark over the full 200k pool). Quoted, not recomputed: this script's job
# is to compare the frozen set against them.
POOL_RATE = {"pooled": 0.1823, "manmade": 0.0387, "moves": 0.1790,
             "hold": 0.1775, "size": 0.3338}


def pool_conflict_rate():
    """Share of the 200k pool with `fit_cost > 0`, from the K2 gate's table."""
    import pandas as pd
    return float((pd.read_parquet("data/pool_beta_c.parquet")["fit_cost"] > 0).mean())


def main():
    t0 = time.perf_counter()
    df = p1.load_items()
    bc = np.empty(len(df))
    for tile in TILES:
        ix = np.where(df["tile"].values == tile)[0]
        bc[ix] = adv.beta_critical_batch(
            adv.build_batch(df.iloc[ix].reset_index(drop=True)))
    fin = np.isfinite(bc)
    fc = df["fit_cost"].values.astype(float)
    conflict = df["conflict"].values.astype(bool)
    n = len(df)

    lines = []
    w = lines.append
    w("# T2 Step 1: `beta_c` on P1's frozen 1,000-item set\n")
    w(f"\nGenerated by `python3 src/frozen_set_beta_c.py` on "
      f"{time.strftime('%Y-%m-%d')}. Deterministic, no seed. "
      f"Measurement only: this script selects nothing and designs nothing.\n")
    w("\nContext: K2 fired (`reports/T2_k2_gate.md`, "
      "`rho_Spearman = -0.9036`), so the `beta_c`-stratified redraw does not "
      "happen and D2's pre-specified fallback is reuse of this frozen set. "
      "These are the counts that fallback would inherit.\n")

    w("\n## 1 and 2. Finite-`beta_c` count and share, against the pool rate\n\n")
    w("| set | N | finite `beta_c` | share | pool rate `\\|D(inf)\\|/N` | difference |\n")
    w("|---|---:|---:|---:|---:|---:|\n")
    rows = [("**pooled**", np.ones(n, bool), "pooled")]
    rows += [(f"`{t}` (\\|O\\| = {adv.tile_k(t)})", df["tile"].values == t, t)
             for t in TILES]
    for name, m, key in rows:
        share = fin[m].mean()
        w(f"| {name} | {int(m.sum()):,} | {int(fin[m].sum()):,} | "
          f"{share:.4f} | {POOL_RATE[key]:.4f} | {share - POOL_RATE[key]:+.4f} |\n")
    w("\nPool rates are quoted from `PREREGISTRATION_v2.1` section 1.2 (T1's "
      "benchmark over the full 200,000-candidate pool), not recomputed here.\n")

    w("\n### Why the frozen set sits above the pool, and why that is not "
      "selection on `beta_c`\n")
    p_conf = conflict.mean()
    r_conf, r_non = fin[conflict].mean(), fin[~conflict].mean()
    pred = p_conf * r_conf + (1 - p_conf) * r_non
    w(f"\nP1's draw is **{p_conf:.0%} conflict by construction**: "
      f"`final_items.py` Step 5 fills a fixed quota of {int(conflict.sum()) // 4} "
      f"conflict and {int((~conflict).sum()) // 4} non-conflict items per tile. "
      f"The pool is {pool_conflict_rate():.4f} conflict. Conflict items are "
      f"where the adversary bites (finite-`beta_c` rate {r_conf:.4f} against "
      f"{r_non:.4f} on non-conflict items), so a set built half of them carries "
      f"a higher finite-`beta_c` rate mechanically:\n\n"
      f"```\n{p_conf:.2f} * {r_conf:.4f}  +  {1 - p_conf:.2f} * {r_non:.4f}"
      f"  =  {pred:.4f}      observed {fin.mean():.4f}\n```\n")
    w("\nThe enrichment is entirely P1's conflict quota, which was fixed for "
      "P1's own reasons before `beta_c` existed as a quantity. Nothing in the "
      "frozen set was selected with any knowledge of `beta_c`, so reusing it "
      "does not select on the dependent variable. A *new* draw that reached for "
      "the same enrichment deliberately would.\n")

    w("\n## 3. The `size` tile against the preregistered target\n\n")
    m = df["tile"].values == "size"
    got = int(fin[m].sum())
    w(f"```\nsize-tile items with finite beta_c   {got}\n"
      f"preregistration v2.0 section 8.2 target   {SIZE_TARGET}  (provisional)\n"
      f"shortfall                                 {max(0, SIZE_TARGET - got)}\n"
      f"fraction of target                        {got / SIZE_TARGET:.3f}\n```\n")
    w(f"\nThe frozen set holds {int(m.sum())} `size`-tile items in total, so "
      f"{SIZE_TARGET} finite-`beta_c` items is not reachable from this set at "
      f"any selection rule: the ceiling is {int(m.sum())} and the observed rate "
      f"is {fin[m].mean():.4f}. The target is provisional in any case "
      f"(section 8.2: `sigma` has never been measured and the 400 is a curve "
      f"over an assumption, not a computed requirement).\n")
    w("\n**Not a licence to enrich.** Arm B's confirmatory analysis set is "
      "defined by finite `beta_c`, so a draw that selected on finite `beta_c` "
      "would be selection on the dependent variable. Section 8.2's own "
      "fallbacks are a larger sample drawn without reference to `beta_c`, or a "
      "stated power limitation.\n")

    w("\n## 4. Conflict-set overlap\n\n")
    w("Of the finite-`beta_c` items, how many carry `fit_cost > 0`:\n\n")
    w("| set | finite `beta_c` | of those, `fit_cost > 0` | share |\n")
    w("|---|---:|---:|---:|\n")
    for name, m, _ in rows:
        f2 = m & fin
        k = int((fc[f2] > 0).sum())
        w(f"| {name} | {int(f2.sum()):,} | {k:,} | "
          f"{k / max(1, int(f2.sum())):.4f} |\n")
    bad = int((conflict != (fc > 0)).sum())
    w(f"\n`fit_cost > 0` and P1's `conflict` flag agree on "
      f"{n - bad:,} of {n:,} items, so the column above is P1's conflict set "
      f"read through `fit_cost`, not a second definition.\n")
    w("\nThe complementary direction, for the same reason the pooled K2 "
      "coefficient came out where it did:\n\n")
    w("| set | N | finite `beta_c` and `fit_cost > 0` | finite `beta_c` and "
      "`fit_cost = 0` |\n|---|---:|---:|---:|\n")
    for name, m, _ in rows:
        f2 = m & fin
        w(f"| {name} | {int(m.sum()):,} | {int((fc[f2] > 0).sum()):,} | "
          f"{int((fc[f2] == 0).sum()):,} |\n")
    w(f"\nAmong conflict items the finite-`beta_c` rate is "
      f"{fin[conflict].mean():.4f} ({int(fin[conflict].sum()):,} of "
      f"{int(conflict.sum()):,}); among non-conflict items it is "
      f"{fin[~conflict].mean():.4f} ({int(fin[~conflict].sum()):,} of "
      f"{int((~conflict).sum()):,}).\n")

    w("\n## Chain of custody\n\n")
    w(f"Spec version `{adv.SPEC_VERSION}`. `beta_c` by "
      f"`adversary.beta_critical_batch` (bisected value of record, "
      f"`eps_beta = {adv.EPS_BETA:g}`).\n\n")
    w("| artifact | sha256 |\n|---|---|\n")
    w(f"| `items_final.parquet` | `{p1.artifact_hash(p1.ITEMS_FINAL)}` |\n")
    w(f"\nRuntime {time.perf_counter() - t0:.1f} s.\n")

    os.makedirs(os.path.dirname(REPORT), exist_ok=True)
    with open(REPORT, "w") as fh:
        fh.write("".join(lines))

    print(f"frozen set N = {n:,}   finite beta_c = {int(fin.sum()):,} "
          f"({fin.mean():.4f}, pool {POOL_RATE['pooled']:.4f})")
    for t in TILES:
        m = df["tile"].values == t
        print(f"  {t:8s} {int(fin[m].sum()):>4} / {int(m.sum()):>4}  "
              f"({fin[m].mean():.4f}, pool {POOL_RATE[t]:.4f})")
    print(f"size tile finite beta_c = {int(fin[df['tile'].values == 'size'].sum())}"
          f"  vs provisional target {SIZE_TARGET}")
    print(f"of {int(fin.sum()):,} finite-beta_c items, "
          f"{int((fc[fin] > 0).sum()):,} have fit_cost > 0")
    print(f"written: {REPORT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
