"""K2, the fit_cost correlation gate (T2 Step 1). Run before anything else in T2.

Preregistration v2.0 section 7.1:

    If |rho_Spearman(beta_c, fit_cost)| >= 0.80 over the full 200,000-candidate
    pool, with beta_c = infinity ranked as the maximum, tied at the top, the
    redraw rationale collapses and the design needs revisiting before Wave 2
    opens.

The Pearson correlation on the finite-beta_c subset is a secondary descriptive
number and is not thresholded. Everything else this script prints is
descriptive too: only the pooled Spearman decides.

`beta_c` comes from T1's `adversary.beta_critical_batch` (spec section 6, the
bisected value of record). `fit_cost` is not recomputed here: it is read from
P1's frozen `items_scored.parquet`, which is the artifact P1's own
`final_items.py` Step 1 wrote (`fit_cost = f(o_fit,h*) - f(o_bayes,h*)`, from
`grid_stats`). Recomputing it in P2 would be a duplication bug.

Deterministic: no seed enters either variable.

Run: python3 src/k2_gate.py      (writes reports/T2_k2_gate.md and the beta_c table)
"""
import os
import sys
import time

import numpy as np
import pandas as pd
from scipy.stats import pearsonr, spearmanr

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import adversary as adv  # noqa: E402
import p1  # noqa: E402

K2_THRESHOLD = 0.80          # preregistration v2.0 section 7.1, fixed pre-data
CHUNK = 20_000
TILES = ("manmade", "moves", "hold", "size")
REPORT = "reports/T2_k2_gate.md"
BETA_C_TABLE = "data/pool_beta_c.parquet"


def pool():
    """The full 200k pool with `fit_cost` attached, item order preserved.

    `items_scored.parquet` is `items_candidate.parquet` plus P1's scores. That
    claim is asserted here rather than trusted, because every number below rests
    on the two files describing the same items in the same order.
    """
    cand = pd.read_parquet(p1.ITEMS_CANDIDATE)
    scored = pd.read_parquet(p1.ITEMS_SCORED)
    if len(cand) != len(scored):
        raise AssertionError(f"pool size mismatch: {len(cand)} vs {len(scored)}")
    for col in ("item_id", "tile", "target_means_pos", "target_clue_pos"):
        if not (cand[col].values == scored[col].values).all():
            raise AssertionError(f"{col} differs between candidate and scored pool")
    for col in ("means", "clues"):
        if not (np.stack(cand[col].values) == np.stack(scored[col].values)).all():
            raise AssertionError(f"{col} differs between candidate and scored pool")
    return scored


def beta_c_over_pool(df):
    """(n,) beta_c aligned to `df`'s row order, by T1's implementation."""
    out = np.empty(len(df))
    for tile in TILES:
        ix = np.where(df["tile"].values == tile)[0]
        sub = df.iloc[ix].reset_index(drop=True)
        out[ix] = np.concatenate([adv.beta_critical_batch(b)
                                  for b in adv.build_batch(sub, chunk=CHUNK)])
    return out


def q(x, ps=(1, 5, 10, 25, 50, 75, 90, 95, 99)):
    return {p: float(np.percentile(x, p)) for p in ps}


def main():
    t0 = time.perf_counter()
    df = pool()
    fc = df["fit_cost"].values.astype(float)
    bc = beta_c_over_pool(df)
    n = len(df)
    robust = np.isinf(bc)

    # The gate. spearmanr ranks +inf as the largest value, ties midranked, which
    # is section 7.1's "ranked as the maximum, tied at the top" verbatim.
    rho, rho_p = spearmanr(bc, fc)
    fired = abs(rho) >= K2_THRESHOLD

    fin = ~robust
    r_pearson, r_p = pearsonr(bc[fin], fc[fin])

    lines = []
    w = lines.append
    w("# T2 Step 1: K2, the `fit_cost` correlation gate\n")
    w(f"Generated by `python3 {__file__.split('deception_RL/')[-1]}` on "
      f"{time.strftime('%Y-%m-%d')}. Deterministic, no seed.\n")
    w("\n## The number\n")
    w(f"\n```\nK2 statistic  rho_Spearman(beta_c, fit_cost) = {rho:+.4f}\n"
      f"threshold     |rho| >= {K2_THRESHOLD:.2f}  (preregistration v2.0 section 7.1)\n"
      f"outcome       {'FIRES. Stop.' if fired else 'does not fire. Gate passes.'}\n"
      f"item base     full candidate pool, N = {n:,}\n```\n")
    w(f"\nComputed over the full pool with `beta_c = infinity` ranked at the "
      f"maximum, tied at the top ({int(robust.sum()):,} items, "
      f"{100*robust.mean():.2f}%). Two-sided p = {rho_p:.3g}, reported because "
      f"the statistic carries one; at N = {n:,} it is not informative and no "
      f"decision reads it.\n")
    w(f"\n**Secondary, descriptive, not thresholded:** Pearson correlation on "
      f"the finite-`beta_c` subset ({int(fin.sum()):,} items) is "
      f"**{r_pearson:+.4f}** (p = {r_p:.3g}).\n")

    w("\n## Tie structure, which a rank correlation on this pool is made of\n")
    zero_fc = fc == 0.0
    w(f"\n- `fit_cost == 0` on **{int(zero_fc.sum()):,}** items "
      f"({100*zero_fc.mean():.2f}%): P1's non-conflict items, where "
      f"`o_fit == o_bayes` by definition, so the cost of choosing rationally is "
      f"exactly zero. They are one midrank block.\n")
    w(f"- `beta_c == infinity` on **{int(robust.sum()):,}** items "
      f"({100*robust.mean():.2f}%): the adversary-robust stratum. One midrank "
      f"block at the top.\n")
    w(f"- Both at once: **{int((zero_fc & robust).sum()):,}** items "
      f"({100*(zero_fc & robust).mean():.2f}%).\n")
    w(f"- Neither: **{int((~zero_fc & ~robust).sum()):,}** items "
      f"({100*(~zero_fc & ~robust).mean():.2f}%).\n")
    w("\nTwo large tie blocks compress the pooled Spearman toward zero relative "
      "to what a within-block relationship could look like. The subgroup "
      "numbers below exist so that compression is visible rather than hidden; "
      "none of them is the gate.\n")

    w("\n## What is driving the number\n")
    w(f"\nThe two tie blocks are very nearly the same set of items:\n\n"
      f"| conditioned on | N | share adversary-robust (`beta_c = inf`) | median finite `beta_c` |\n"
      f"|---|---:|---:|---:|\n")
    for name, m in (("`fit_cost == 0` (non-conflict)", zero_fc),
                    ("`fit_cost > 0` (conflict)", ~zero_fc)):
        f2 = m & fin
        w(f"| {name} | {int(m.sum()):,} | {100*robust[m].mean():.2f}% | "
          f"{np.median(bc[f2]):.4f} |\n")
    w("\nBoth variables are, structurally, the same kind of statement: "
      "`fit_cost = 0` says P1's fit-maximizing option is already the "
      "posterior-maximizing option, and `beta_c = infinity` says the "
      "posterior-maximizing option is already the margin-maximizing option. "
      "On this pool those two coincidences co-occur, and the conditional rates "
      "above are the whole of the pooled rank correlation. Items where the "
      "Scientist gives up nothing by choosing rationally are also the items the "
      "adversary cannot move, and the sign is negative because among the "
      "remainder a larger `fit_cost` goes with a smaller budget needed to flip "
      "the optimum.\n")

    w("\n**Cross-check on `beta_c` itself.** The existence rate implied here, "
      f"`|D(infinity)| / N = {fin.mean():.4f}`, reproduces the value T1's "
      "benchmark computed independently on the same pool (0.1823, "
      "`reports/T1_benchmark.md`, disclosed as K1's statistic in "
      "`docs/P2/PREREGISTRATION_v2.1.md` section 1.2). The gate statistic is "
      "not resting on a fresh, unchecked `beta_c` run.\n")

    w("\n## Descriptive breakdowns (none of these is the gate)\n\n")
    rows = [("pooled", n, rho, r_pearson)]
    for tile in TILES:
        m = df["tile"].values == tile
        rt = spearmanr(bc[m], fc[m])[0]
        f2 = m & fin
        rp = pearsonr(bc[f2], fc[f2])[0] if f2.sum() > 2 else float("nan")
        rows.append((f"`{tile}` (|O| = {adv.tile_k(tile)})", int(m.sum()), rt, rp))
    m = ~zero_fc
    rows.append(("conflict items only (`fit_cost > 0`)", int(m.sum()),
                 spearmanr(bc[m], fc[m])[0],
                 pearsonr(bc[m & fin], fc[m & fin])[0]))
    m = zero_fc
    rows.append(("non-conflict only (`fit_cost == 0`)", int(m.sum()),
                 float("nan"), float("nan")))
    w("| subset | N | Spearman rho | Pearson r (finite `beta_c`) |\n")
    w("|---|---:|---:|---:|\n")
    for name, ni, a, b in rows:
        sa = "n/a, constant" if np.isnan(a) else f"{a:+.4f}"
        sb = "n/a, constant" if np.isnan(b) else f"{b:+.4f}"
        w(f"| {name} | {ni:,} | {sa} | {sb} |\n")
    w("\n`fit_cost` is identically zero on the non-conflict items, so no "
      f"correlation is defined there. That row is listed rather than dropped: "
      f"it is {100*zero_fc.mean():.1f}% of the pool and its absence from the "
      "other rows is a fact about the statistic, not an exclusion.\n")
    w("\n**For the author, flagged and not acted on.** The gate is the pooled "
      "row, and the pooled row fires. The conflict-only row is well below the "
      "threshold, and it is the subset P1 actually stratified on: "
      "`final_items.py` Step 5 cuts `fit_cost` deciles over conflict items only "
      "and stratifies the non-conflict half on `decision_margin` instead. So "
      "the pooled statistic the preregistration names and the base P1's draw "
      "used are not the same base. That is a fact about the two documents, not "
      "a reading of the gate: preregistration v2.0 section 7.1 specifies the "
      "full pool, section 7.1 also says a fired K2 'is not resolved by "
      "re-picking the stratification variable inside the same session', and "
      "this session has not done so.\n")

    w("\n## `beta_c` marginal, for the record\n\n")
    qq = q(bc[fin])
    w(f"Finite on {int(fin.sum()):,} of {n:,} items ({100*fin.mean():.2f}%), "
      f"infinite on {int(robust.sum()):,} ({100*robust.mean():.2f}%). "
      f"Exactly zero on {int((bc == 0).sum()):,} (boundary-tied, spec section "
      f"7.1). Percentiles of the finite part:\n\n")
    w("| " + " | ".join(f"p{p}" for p in qq) + " |\n")
    w("|" + "---:|" * len(qq) + "\n")
    w("| " + " | ".join(f"{v:.4f}" for v in qq.values()) + " |\n")

    w("\n## Chain of custody\n\n")
    w(f"Spec version `{adv.SPEC_VERSION}`, `docs/spec/adversary-game-v1.md`. "
      f"`beta_c` by `adversary.beta_critical_batch` (bisected value of record, "
      f"`eps_beta = {adv.EPS_BETA:g}`). `fit_cost` read from P1's frozen "
      f"artifact, not recomputed.\n\n")
    w("| artifact | sha256 |\n|---|---|\n")
    for name, path in (("items_candidate.parquet", p1.ITEMS_CANDIDATE),
                       ("items_scored.parquet", p1.ITEMS_SCORED),
                       ("items_final.parquet", p1.ITEMS_FINAL)):
        w(f"| `{name}` | `{p1.artifact_hash(path)}` |\n")
    w(f"\nRuntime {time.perf_counter() - t0:.1f} s.\n")

    os.makedirs(os.path.dirname(REPORT), exist_ok=True)
    with open(REPORT, "w") as fh:
        fh.write("".join(lines))

    os.makedirs(os.path.dirname(BETA_C_TABLE), exist_ok=True)
    pd.DataFrame({"item_id": df["item_id"].values, "tile": df["tile"].values,
                  "beta_c": bc, "is_robust": robust, "fit_cost": fc}
                 ).to_parquet(BETA_C_TABLE, index=False)

    print(f"K2  rho_Spearman(beta_c, fit_cost) = {rho:+.4f}   "
          f"threshold |rho| >= {K2_THRESHOLD:.2f}   "
          f"{'FIRES' if fired else 'does not fire'}")
    print(f"    secondary Pearson on finite subset = {r_pearson:+.4f} "
          f"({int(fin.sum()):,} items), not thresholded")
    print(f"    written: {REPORT}, {BETA_C_TABLE}")
    return 1 if fired else 0


if __name__ == "__main__":
    sys.exit(main())
